const x = {
  code: 200,
  currentTime: 1571466065928,
  data: {
    entry: {
      arrivalsAndDepartures: [
        {
          arrivalEnabled: true,
          blockTripSequence: 0,
          departureEnabled: true,
          distanceFromStop: 1161.7977207909234,
          frequency: null,
          lastUpdateTime: 0,
          numberOfStopsAway: 3,
          predicted: false,
          predictedArrivalInterval: null,
          predictedArrivalTime: 0,
          predictedDepartureInterval: null,
          predictedDepartureTime: 0,
          routeId: "15_101",
          routeLongName: "JNAMBA042",
          routeShortName: "42A",
          scheduledArrivalInterval: null,
          scheduledArrivalTime: 1571466262000,
          scheduledDepartureInterval: null,
          scheduledDepartureTime: 1571466262000,
          serviceDate: 1571454000000,
          situationIds: [],
          status: "default",
          stopId: "82_203849",
          stopSequence: 21,
          tripHeadsign: "a Alcorta",
          tripId: "15_560-1",
          tripStatus: {
            activeTripId: "15_560-1",
            blockTripSequence: 0,
            closestStop: "82_205144",
            closestStopTimeOffset: -35,
            distanceAlongTrip: 0,
            frequency: null,
            lastKnownDistanceAlongTrip: 0,
            lastKnownLocation: null,
            lastKnownOrientation: 0,
            lastLocationUpdateTime: 0,
            lastUpdateTime: 0,
            nextStop: "82_203997",
            nextStopTimeOffset: 51,
            orientation: 347.09172494380147,
            phase: "",
            position: { lat: -34.562296101692255, lon: -58.442448126282784 },
            predicted: false,
            scheduleDeviation: 0,
            scheduledDistanceAlongTrip: 7222.637407840851,
            serviceDate: 1571454000000,
            situationIds: [],
            status: "default",
            totalDistanceAlongTrip: 22524.272833027237,
            vehicleId: "",
            vehicleLabel: ""
          },
          vehicleId: "",
          vehicleLabel: ""
        },
        {
          arrivalEnabled: true,
          blockTripSequence: 0,
          departureEnabled: true,
          distanceFromStop: 8384.435128631774,
          frequency: null,
          lastUpdateTime: 0,
          numberOfStopsAway: 21,
          predicted: false,
          predictedArrivalInterval: null,
          predictedArrivalTime: 0,
          predictedDepartureInterval: null,
          predictedDepartureTime: 0,
          routeId: "15_101",
          routeLongName: "JNAMBA042",
          routeShortName: "42A",
          scheduledArrivalInterval: null,
          scheduledArrivalTime: 1571468062000,
          scheduledDepartureInterval: null,
          scheduledDepartureTime: 1571468062000,
          serviceDate: 1571454000000,
          situationIds: [],
          status: "default",
          stopId: "82_203849",
          stopSequence: 21,
          tripHeadsign: "a Alcorta",
          tripId: "15_561-1",
          tripStatus: {
            activeTripId: "15_561-1",
            blockTripSequence: 0,
            closestStop: "82_2032080",
            closestStopTimeOffset: 535,
            distanceAlongTrip: 0,
            frequency: null,
            lastKnownDistanceAlongTrip: 0,
            lastKnownLocation: null,
            lastKnownOrientation: 0,
            lastLocationUpdateTime: 0,
            lastUpdateTime: 0,
            nextStop: "82_2032080",
            nextStopTimeOffset: 535,
            orientation: 342.674647622533,
            phase: "",
            position: { lat: -34.54226, lon: -58.444955 },
            predicted: false,
            scheduleDeviation: 0,
            scheduledDistanceAlongTrip: 0,
            serviceDate: 1571454000000,
            situationIds: [],
            status: "default",
            totalDistanceAlongTrip: 22524.272833027237,
            vehicleId: "",
            vehicleLabel: ""
          },
          vehicleId: "",
          vehicleLabel: ""
        }
      ],
      nearbyStopIds: ["82_203852", "82_203844"],
      situationIds: [],
      stopId: "82_203849"
    },
    references: {
      agencies: [
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "15",
          lang: "ES",
          name: "TRANSPORTES COLEGIALES S.A.C.I.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "41",
          lang: "ES",
          name: "VUELTA DE ROCHA S.A.T.C.I.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "3",
          lang: "ES",
          name: "D.O.T.A. S.A. DE TRANSPORTE AUTOMOTOR",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "87",
          lang: "ES",
          name: "TRANSPORTES ALMIRANTE BROWN S.A.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "36",
          lang: "ES",
          name: "JUAN B. JUSTO S.A.T.C.I.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "51",
          lang: "ES",
          name: "4 DE SEPTIEMBRE S.A.T.C.P.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "83",
          lang: "ES",
          name: "MICROOMNIBUS CUARENTA Y CINCO S.A.C.I.F.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "4",
          lang: "ES",
          name: "NUDO S.A.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "64",
          lang: "ES",
          name: "MICRO OMNIBUS SUR S.A.C.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "84",
          lang: "ES",
          name: "MICROOMNIBUS CIUDAD DE BS.AS. S.A.T.C.I",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "49",
          lang: "ES",
          name: "AZUL S.A. DE TRANSPORTE AUTOMOTOR",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "30",
          lang: "ES",
          name: "BERNARDINO RIVADAVIA S.A.T.A.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        },
        {
          disclaimer: "",
          email: "",
          fareUrl: "",
          id: "85",
          lang: "ES",
          name: "TRANSPORTES DEL TEJAR S.A.",
          phone: "",
          privateService: false,
          timezone: "America/Argentina/Buenos_Aires",
          url: "https://www.argentina.gob.ar/cnrt"
        }
      ],
      routes: [
        {
          agencyId: "15",
          color: "",
          description: "Alcorta - Cdad. Universitaria",
          id: "15_101",
          longName: "JNAMBA042",
          shortName: "42A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "15",
          color: "",
          description: "Alcorta - Cdad. Universitaria",
          id: "15_455",
          longName: "JNAMBA042",
          shortName: "42B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "41",
          color: "",
          description: "La Boca - Est. Belgrano x Htal. Militar",
          id: "41_340",
          longName: "JNAMBA064",
          shortName: "64A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "41",
          color: "",
          description: "La Boca - Est. Belgrano x Hipodromo",
          id: "41_341",
          longName: "JNAMBA064",
          shortName: "64B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "41",
          color: "",
          description: "Av. Paseo Colón y Av. Juan de Garay - Est. Belgrano",
          id: "41_342",
          longName: "JNAMBA064",
          shortName: "64C",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "41",
          color: "",
          description:
            "Av. Paseo Colón y Av. Juan de Garay - Est. Belgrano x Hipodromo",
          id: "41_1044",
          longName: "JNAMBA064",
          shortName: "64D",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "3",
          color: "",
          description: "Pte. Alsina - Cdad. Universitaria",
          id: "3_83",
          longName: "JNAMBA028",
          shortName: "28D",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "3",
          color: "",
          description: "Liniers - Cdad. Universitaria",
          id: "3_81",
          longName: "JNAMBA028",
          shortName: "28F",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "3",
          color: "",
          description: "Term. Ómnibus Pte. La Noria - Cdad. Universitaria",
          id: "3_79",
          longName: "JNAMBA028",
          shortName: "28H",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "3",
          color: "",
          description: "Term. Ómnibus Pte. La Noria - Cdad. Universitaria",
          id: "3_443",
          longName: "JNAMBA028",
          shortName: "28J",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "3",
          color: "",
          description: "Liniers - Cdad. Universitaria",
          id: "3_78",
          longName: "JNAMBA028",
          shortName: "28K",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "87",
          color: "",
          description:
            "Cdad. Universitaria - Monte Chongolo x Barracas y Gral. Madariaga",
          id: "87_273",
          longName: "JNAMBA033",
          shortName: "33A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "87",
          color: "",
          description:
            "Cdad. Universitaria - Monte Chongolo x Barracas y Cement. de Avellaneda",
          id: "87_274",
          longName: "JNAMBA033",
          shortName: "33B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "87",
          color: "",
          description:
            "Cdad. Universitaria - Monte Chongolo x Dock Sud y Gral. Madariaga",
          id: "87_275",
          longName: "JNAMBA033",
          shortName: "33C",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "87",
          color: "",
          description:
            "Cdad. Universitaria - Monte Chongolo x Dock Sud y Cement. de Avellaneda",
          id: "87_276",
          longName: "JNAMBA033",
          shortName: "33D",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "36",
          color: "",
          description: "Cdad. Universitaria - Est. Liniers",
          id: "36_469",
          longName: "JNAMBA034",
          shortName: "34B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "36",
          color: "",
          description: "Semirápido - Cdad. Universitaria - Est. Liniers",
          id: "36_1742",
          longName: "JNAMBA034",
          shortName: "34E",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "51",
          color: "",
          description: "Est. Lanus - Pza. Italia",
          id: "51_325",
          longName: "JNAMBA037",
          shortName: "37A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "51",
          color: "",
          description: "Est. Lanus - Cdad. Universitaria x Av. F. Alcorta",
          id: "51_326",
          longName: "JNAMBA037",
          shortName: "37B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "83",
          color: "",
          description: "Cdad. Universitaria - Remedios de Escalada",
          id: "83_203",
          longName: "JNAMBA045",
          shortName: "45A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "83",
          color: "",
          description: "Cdad. Universitaria - Pza. Constitución",
          id: "83_304",
          longName: "JNAMBA045",
          shortName: "45C",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "83",
          color: "",
          description: "Expreso - Retiro - Cdad. Universitaria",
          id: "83_305",
          longName: "JNAMBA045",
          shortName: "45D",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "4",
          color: "",
          description: "Eva Peron - Cdad. Universitaria",
          id: "4_102",
          longName: "JNAMBA107",
          shortName: "107A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "4",
          color: "",
          description: "Cdad. Universitaria - Av. La Salle y E. Peron",
          id: "4_1801",
          longName: "JNAMBA107",
          shortName: "107B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description:
            "Cdad. Universitaria - Bº Don Oriono x Aguas Arg.. y Alsina",
          id: "64_263",
          longName: "JNAMBA160",
          shortName: "160A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description:
            "Cdad. Universitaria - Bº Don Oriono x Aguas Arg.. y Joaquin V. González",
          id: "64_264",
          longName: "JNAMBA160",
          shortName: "160B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description:
            "Cdad. Universitaria - Bº Don Oriono x Aeroparque y Alsina",
          id: "64_265",
          longName: "JNAMBA160",
          shortName: "160C",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description:
            "Cdad. Universitaria - Bº Don Oriono x Aeroparque y Joaquien González",
          id: "64_266",
          longName: "JNAMBA160",
          shortName: "160D",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description: "Cdad. Universitaria - Est. Lanus x Aguas Arg.entinas",
          id: "64_269",
          longName: "JNAMBA160",
          shortName: "160G",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description: "Cdad. Universitaria - Nueva Pompeya x Aeroparque",
          id: "64_1744",
          longName: "JNAMBA160",
          shortName: "160H",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description: "Cdad. Universitaria - Nueva Pompeya x Aguas Arg.",
          id: "64_1747",
          longName: "JNAMBA160",
          shortName: "160K",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description: "Cdad. Universitaria - Est. Lanus x Aeroparque",
          id: "64_1748",
          longName: "JNAMBA160",
          shortName: "160L",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "64",
          color: "",
          description:
            "Expreso x Aguas Arg.. - Cdad. Universitaria - Pza. Italia",
          id: "64_1750",
          longName: "JNAMBA160",
          shortName: "160N",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "84",
          color: "",
          description:
            "Ramal 1 - Est. BsAs x Est. La Lucila A Int. Cnel. A. Ávalos y D. De Acassuso",
          id: "84_210",
          longName: "JNAMBA059",
          shortName: "59A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "84",
          color: "",
          description:
            "Ramal 2 - Est. BsAs x Bº Golf - Int. Cnel. A. Ávalos y D. De Acassuso",
          id: "84_284",
          longName: "JNAMBA059",
          shortName: "59B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "84",
          color: "",
          description: "Ramal 3 - Est. BsAs - PUENTE SAAVEDRA",
          id: "84_285",
          longName: "JNAMBA059",
          shortName: "59C",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "49",
          color: "",
          description: "San Cristóbal - Munro x Viaducto Carranza",
          id: "49_331",
          longName: "JNAMBA041",
          shortName: "41A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "30",
          color: "",
          description: "Est. Belgrano - Villa Madero",
          id: "30_134",
          longName: "JNAMBA063",
          shortName: "63A",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "30",
          color: "",
          description: "Est. Belgrano - Villa Madero x Coronel Pagola",
          id: "30_135",
          longName: "JNAMBA063",
          shortName: "63B",
          textColor: "",
          type: 3,
          url: ""
        },
        {
          agencyId: "85",
          color: "",
          description: "Htal. Rawson - Villa Martelli x Viaducto Carranza",
          id: "85_211",
          longName: "JNAMBA067",
          shortName: "67A",
          textColor: "",
          type: 3,
          url: ""
        }
      ],
      situations: [],
      stops: [
        {
          code: "203849",
          direction: "SW",
          id: "82_203849",
          lat: -34.569182,
          locationType: 0,
          lon: -58.44533,
          name: "2373 GARCIA TEODORO",
          routeIds: ["15_101", "15_455"],
          wheelchairBoarding: "UNKNOWN"
        },
        {
          code: "205144",
          direction: "SE",
          id: "82_205144",
          lat: -34.561575,
          locationType: 0,
          lon: -58.444517,
          name: "1622 VERTIZ VIRREY AV.",
          routeIds: ["15_101", "41_340", "41_341", "41_342", "41_1044"],
          wheelchairBoarding: "UNKNOWN"
        },
        {
          code: "203997",
          direction: "SE",
          id: "82_203997",
          lat: -34.562988,
          locationType: 0,
          lon: -58.439985,
          name: "1318 MIGUELETES",
          routeIds: ["15_101", "41_340", "41_341", "41_342", "41_1044"],
          wheelchairBoarding: "UNKNOWN"
        },
        {
          code: "2032080",
          direction: "E",
          id: "82_2032080",
          lat: -34.54226,
          locationType: 0,
          lon: -58.444955,
          name: "CIUDAD UNIVERSITARIA",
          routeIds: [
            "3_83",
            "3_81",
            "3_79",
            "3_443",
            "3_78",
            "87_273",
            "87_274",
            "87_275",
            "87_276",
            "36_469",
            "36_1742",
            "51_325",
            "51_326",
            "15_101",
            "15_455",
            "83_203",
            "83_304",
            "83_305",
            "4_102",
            "4_1801",
            "64_263",
            "64_264",
            "64_265",
            "64_266",
            "64_269",
            "64_1744",
            "64_1747",
            "64_1748",
            "64_1750"
          ],
          wheelchairBoarding: "UNKNOWN"
        },
        {
          code: "203852",
          direction: "NE",
          id: "82_203852",
          lat: -34.569465,
          locationType: 0,
          lon: -58.444388,
          name: "2362 LACROZE FEDERICO AV.",
          routeIds: ["84_210", "84_284", "84_285"],
          wheelchairBoarding: "UNKNOWN"
        },
        {
          code: "203844",
          direction: "NW",
          id: "82_203844",
          lat: -34.569272,
          locationType: 0,
          lon: -58.44629,
          name: "983 CABILDO AV.",
          routeIds: ["49_331", "30_134", "30_135", "85_211"],
          wheelchairBoarding: "UNKNOWN"
        }
      ],
      trips: [
        {
          blockId: "15_101SI1007",
          directionId: "1",
          id: "15_560-1",
          routeId: "15_101",
          routeShortName: "",
          serviceId: "82_1",
          shapeId: "82_8",
          timeZone: "",
          tripHeadsign: "a Alcorta",
          tripShortName: "101SI1007"
        },
        {
          blockId: "15_101SI1008",
          directionId: "1",
          id: "15_561-1",
          routeId: "15_101",
          routeShortName: "",
          serviceId: "82_1",
          shapeId: "82_8",
          timeZone: "",
          tripHeadsign: "a Alcorta",
          tripShortName: "101SI1008"
        }
      ]
    }
  },
  text: "OK",
  version: 2
};
